### ISSUE TITLE
locking mechanism for concurrent editing of annotations

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#170]
when concurrent users are trying to edit the same annotation, allow only one user to modify the annotation and prevent other users from editing the annotation

**Comment by MarcusBarnes** [comment]
Noting https://github.com/discoverygarden/islandora_object_lock for reference.

**Comment by kimpham54** [comment]
you might also want to look at https://jira.duraspace.org/browse/ISLANDORA-1556

**Comment by kstapelfeldt** [comment]
We have a conflict resolution mechanism. If two people are editing at the same time, and one person saves it, we send a notice to the second person indicating that the changes cannot be saved. Not a blocker for release. Putting a note in the documentation so that users know what to expect when multiple people may be editing the same annotation is a good idea.

**Comment by kimpham54** [comment]
documented here: https://github.com/digitalutsc/islandora_web_annotations/wiki/Edge-Case-Behaviour
