### ISSUE TITLE
An annotation does not load in the interface and exists in Fedora. Can make multiple annotation containers.

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_web_annotations#58]
1. Created a new large image object as admin
2. Masqueraded as an authenticated user with permission to create web annotations (user has been successfully used to create annotations in this instance) and created an annotation. I received confirmation that annotation was created. (I did not check to see if the block underneath was updated. I'm sorry for that.)
2. Switched to a different authenticated user and attempt to load annotations. Annotation does not load. 
4. Switched to admin account and verified that annotation won't load for this user either. Also verify that the annotation and annotation container was created (by directly navigating to expected PID via URL)
5. As Admin, created an annotation successfully. Other test users can load the annotation. 
6. Navigate to expected PID using the browser URL as admin. Discover that a second annotation container has been created at expected PID. Verified that two annotation containers were created for a single islandora object. 

#s are a little arbitrary here - criticize my reporting technique! Happy to provide additional details/reformat.

**Comment by MarcusBarnes** [comment]
@Natkeeran and myself have been unable to reproduce.  @kstapelfeldt, would you please clone the most recent master and confirm that you're still able produce the issue?  If you're able to reproduce from the latest commits,  would you please provide detailed steps (again) so that we can attempt to reproduce?  Thank you.

**Comment by MarcusBarnes** [comment]
@kstapelfeldt I was able to reproduce when switching users as you described using the [Masquerade module](https://www.drupal.org/project/masquerade).  I will investigate further.

**Comment by MarcusBarnes** [comment]
When creating annotations as certain classes of users, the created objects are inactive in Fedora (including the AnnotationContainer objects).

The following addresses the issue.  

1.  Enable the Islandora Simple Workflow module.
2.  For the roles with create annotation permissions, make sure that these roles also have the `Bypass default inactive object state`  permission provided by Islandora Simple Workflow.

Annotation related objects will then be created in an active state in Fedora, allowing the annotation view and creation to continue as expected.

**Comment by kstapelfeldt** [comment]
This works. Also, if I turn off Simple Workflow module in the VM, I can't recreate the issue.

**Comment by MarcusBarnes** [comment]
@kstapelfeldt and @Natkeeran point out that this issue is related to the Islandora Simple Workflow module.   If it is off, everything works as expected.  If the module is enabled, you will need to follow the steps in comment https://github.com/digitalutsc/islandora_web_annotations/issues/58#issuecomment-274589156.  The issue arises because when Islandora Simple Workflow module is enabled, new objects are given the Inactive state.

**Comment by MarcusBarnes** [comment]
I'll create a sperate issue to document the above issue with Islandora Simple Workflow.
